### ISSUE TITLE
Running examples/android

### ISSUE THREAD

**Issue by umkhanqta** [S2-group/android-runner#49]
I tried to run the example in examples/android
but I am getting the following error

Python3: after_run.py
Profilers: Collecting results
NativeExperiment: Sleeping for 500 milliseconds
Profilers: Start subject aggregation
NativeExperiment: Experiment completed, start cleanup
Python3: after_experiment.py
Profilers: Stop profiling
Profilers: Unloading
Profilers: Start final aggregation
Python3: aggregate_android.py
Output file: /home/umair/Desktop/android-runner-master/android-runner/examples/android/output/2020.09.03_193603/Aggregated_Results_Android.csv
root: ScriptError: KeyError in aggregate_android.py: 'android_cpu'
Traceback (most recent call last):
  File "android-runner/AndroidRunner/Script.py", line 33, in mp_run
    output = self.execute_script(device, *args, **kwargs)
  File "android-runner/AndroidRunner/Python3.py", line 19, in execute_script
    return self.module.main(device, *args, **kwargs)
  File "/home/umair/Desktop/android-runner-master/android-runner/examples/android/Scripts/aggregate_android.py", line 64, in main
    rows = aggregate(data_dir)
  File "/home/umair/Desktop/android-runner-master/android-runner/examples/android/Scripts/aggregate_android.py", line 42, in aggregate
    row.update(aggregate_android_final(os.path.join(subject_dir, 'android')))
  File "/home/umair/Desktop/android-runner-master/android-runner/examples/android/Scripts/aggregate_android.py", line 28, in aggregate_android_final
    runs_total = reduce(lambda x, y: {k: v + y[k] for k, v in list(x.items())}, runs)
  File "/home/umair/Desktop/android-runner-master/android-runner/examples/android/Scripts/aggregate_android.py", line 28, in <lambda>
    runs_total = reduce(lambda x, y: {k: v + y[k] for k, v in list(x.items())}, runs)
  File "/home/umair/Desktop/android-runner-master/android-runner/examples/android/Scripts/aggregate_android.py", line 28, in <dictcomp>
    runs_total = reduce(lambda x, y: {k: v + y[k] for k, v in list(x.items())}, runs)
KeyError: 'android_cpu'

root: An error occurred, the experiment has been stopped. To continue, add progress file argument to experiment startup: --progress /home/umair/Desktop/android-runner-master/android-runner/examples/android/output/2020.09.03_193603/progress.xml

**Comment by EricZielinski** [comment]
Hello,

Thanks for letting us know.  Seems like the experiment_aggregation field was changed in the last merge.  I changed it from `Scripts/aggregate_android.py` to `default` and it worked.  See below.  We'll update the repo accordingly.
```
  "profilers": {
    "android": {
      "subject_aggregation": "default",
      **"experiment_aggregation": "default",**
      "sample_interval": 100,
      "data_points": [
        "cpu",
        "mem"
      ]
    }
```

**Comment by umkhanqta** [comment]
Thanks a lot now
